NovaSky-AI/SkyRL

- examples/sky/README.md
Small fix to the README to make it clear how exactly to download the dataset and what the relation to the DATA_DIR exactly is. Uses the existing uv environment to do the download.
> Add more concrete instruction on how to download dataset

- skyrl-train/docs/configuration/config.rst
- skyrl-train/docs/examples/ppo.rst
- skyrl-train/docs/examples/remote_server.rst
- skyrl-train/docs/getting-started/quickstart.rst
- skyrl-train/examples/multiply/run_multiply.sh
- skyrl-train/scripts/full_context/run_full_ctx.sh
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
Change `test.parquet` to `validation.parquet` across scripts and docs to stay consistent.
Change `["x"]` to `"['x']"` which is needed for bash to interpret lists with multiple items (we already do it in most places, only a few places missing)
> [fix] In docs and scripts, test->validation.parquet, and ["x"] -> "['x']"

- skyrl-train/skyrl_train/inference_engines/utils.py
I was getting this error when passing adding stop tokens to generator config by passing a `"stop": [token1, token2, ...]`
```
(VLLMInferenceEngine pid=132934)   File "/home/ubuntu/.cache/uv/builds-v0/.tmpqd4VTJ/lib/python3.12/site-packages/vllm/sampling_params.py", line 378, in __post_init__
(VLLMInferenceEngine pid=132934)     self._verify_args()
(VLLMInferenceEngine pid=132934)   File "/home/ubuntu/.cache/uv/builds-v0/.tmpqd4VTJ/lib/python3.12/site-packages/vllm/sampling_params.py", line 444, in _verify_args
(VLLMInferenceEngine pid=132934)     assert isinstance(self.stop, list)
(VLLMInferenceEngine pid=132934)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VLLMInferenceEngine pid=132934) AssertionError
```
this change fixes it, stop tokens can be added to generator config
> fix: Updated utils.py to fix stop token issue

- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/config/skyrl_gym_config/default.yaml
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator_chat_templating.py
- skyrl-train/tests/gpu/test_skyrl_gym_generator.py
Previously, we were blocking the asyncio event loop on each `env.step()` call
https://github.com/NovaSky-AI/SkyRL/blob/160291f048fa719ba90ca14773102165c9b34eaa/skyrl-train/skyrl_train/generators/skyrl_gym_generator.py#L269
This PR updates the `SkyRLGymGenerator` to use a simple `ThreadPoolExecutor` to allow trajectories to call synchronous env.step without blocking the main event loop
Using a basic multi-turn env with 3 max turns that just calls time.sleep(3)
```
class TestEnv(BaseTextEnv):
...
def step(self, action: str):
...
time.sleep(3)
...
```
we see a speedup from > 30 mins (3s * 3 turns * 256 samples) to < 4 min
Before: 
After:
> [generator] Add `max_env_workers` argument for generator thread pool executor

- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
Ensure that `stop_reason` is set **before** truncating `loss_mask` and `response_ids` to maintain correct logic and avoid inconsistencies.
> fix: move `stop_reason` checking logic before list truncation

- .pre-commit-config.yaml
Adds a pre-commit hook for gitleaks. We currently commit certain example `.env` files, like `.env.example` , and this hook ensures that developers don't accidentally commit secret keys. 
I've tested whether this works by using a real WandB API Key and I got the following error:
```bash
(base) ray@ip-10-0-155-108:~/default/torchupdate$ git commit -s -m "x"
ruff.................................................(no files to check)Skipped
black................................................(no files to check)Skipped
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1
○
│╲
│ ○
○ ░
░    gitleaks
Finding:     WANDB_API_KEY=REDACTED
Secret:      REDACTED
RuleID:      generic-api-key
Entropy:     3.625071
File: …
```
> Add pre-commit hook for gitleaks

- .github/workflows/cpu_ci.yaml
- skyrl-train/docs/getting-started/installation.rst
Adds documentation for running on an existing ray cluster with a different ray version. Currently, we use a uv lockfile to pin all dependencies, so this PR adds some instructions for overriding the ray version. To make sure as many users as possible to through the same "golden path", we will have one recommended Ray version that is pinned and well-tested. In the future as we get more CI testing bandwidth, we will expand the support to more Ray versions.
> [Docs] Add docs for running on an existing ray cluster

- skyrl-train/skyrl_train/generators/utils.py
- skyrl-train/skyrl_train/trainer.py
- skyrl-train/tests/cpu/test_generator_postprocess.py
Supports per-token rewards from the generator. Currently, the postprocess_generator_output function is hardcoded to only support per-sequence rewards, but we should be able to easily support per-token rewards. 
I've also added a test to make sure that the postprocessing function is tested. This is placed in a new file for ease of use.
> [Trainer] Support per-token rewards in trainer

- skyrl-train/skyrl_train/utils/utils.py
- skyrl-train/tests/gpu/gpu_ci/conftest.py
After #73, the main code path no longer runs on GPUs without P2P support (potentially due to cuda 12.8 upgrade?) - an error would be thrown like
```bash
torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:3353, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 217 'peer access is not supported between these two devices'
```
This PR adds a check for whether peer access is supported (using torch/cuda) between all GPUs on a node to the ray initialization, and sets relevant NCCL env vars to allow the code to run on these machine types.
```python
if not peer_access_supported():
logger.info("Peer access is not supported, disabling …
```
> Add check for whether p2p access is supported - allows code to run on L4/L40S after #73 upgrade to cuda 12.8

- docker/Dockerfile
- docker/Dockerfile.ray244
- skyrl-train/README.md
- skyrl-train/ci/anyscale_gpu_ci.yaml
- skyrl-train/docs/getting-started/installation.rst
- skyrl-train/pyproject.toml
- skyrl-train/uv.lock
Upgrades ray to 2.48.0, which allows us to remove the pip install vllm in the Dockerfile as a fallback for when uv + vllm does not resolve dependencies with the vllm + ray backend correctly.
We leave the previous Dockerfile in `docker/Dockerfile.ray244` for backwards compatibility
> [dependencies] Upgrade ray to 2.48.0

- skyrl-train/ci/gpu_ci_run.sh
- skyrl-train/skyrl_train/utils/utils.py
- skyrl-train/tests/gpu/gpu_ci/conftest.py
missed an argument in `gpu_ci/conftest.py` for `peer_access_supported()` - fix for gpu ci to run 
Passing now with update:
And main runs (and disables p2p access) correctly:
> fix issue with #108 that broke gpu ci

- skyrl-train/docs/getting-started/installation.rst
Adds a warning for uv versions 0.8.0, 0.8.1 and 0.8.2 due to a bug in the uv run --with flag for "Running in ray cluster" section. These are relatively new versions and thus it's better to have this detail in the documentation for users.
> Add warning for certain uv versions due to `uv run --with` regression

- .github/workflows/gpu_ci.yaml
Adds filters with `paths`  for the GPU CI workflow so that it's only triggered for relevant changes in skyrl-train. 
Note that technically we have some dependencies with `skyrl-gym` at the moment, but for the GPU CI workflow, we will focus on unit and integration tests for `skyrl-train` and thus we should be okay ignoring changes in `skyrl-gym`.
> [GPU CI] Only trigger workflow for relevant changes in `skyrl-train`

- skyrl-train/docs/configuration/config.rst
- skyrl-train/examples/gsm8k/run_gsm8k.sh
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
- skyrl-train/skyrl_train/generators/utils.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator_chat_templating.py
- skyrl-train/tests/cpu/generators/test_utils.py
Adds `apply_overlong_filtering` to the generator config, and provides a generator utility method `apply_overlong_filtering()` for post-processing the loss mask.
I originally implemented this using the `stop_reasons` to determine whether the sequence was truncated, but instead switched to looking for `eos_token` in the response IDs for a more general approach.
Added CPU tests for the utility method and for SkyRL Gym Generator's use of the utility method.
> [DAPO] Add support for overlong filtering

- skyrl-train/examples/http_server/rollout_with_http_server_litellm.py
- skyrl-train/examples/http_server/run_gsm8k_with_http_server.sh
- skyrl-train/examples/rollout_with_http_server_litellm.py
- skyrl-train/pyproject.toml
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/entrypoints/main_base.py
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
- skyrl-train/skyrl_train/inference_engines/inference_engine_client.py
- skyrl-train/skyrl_train/inference_engines/launch_inference_engine_http_server.py
- skyrl-train/skyrl_train/inference_engines/openai_api_protocol.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator.py
- skyrl-train/tests/cpu/http/test_openai_request_utils.py
- skyrl-train/tests/gpu/test_engine_generation.py
- skyrl-train/tests/gpu/test_http_inference_engine_client.py
- skyrl-train/tests/gpu/test_policy_vllm_e2e.py
- skyrl-train/tests/gpu/test_skyrl_gym_generator.py
- skyrl-train/tests/sglang/test_policy_sglang_e2e.py
- skyrl-train/uv.lock
This is a first stab for https://github.com/NovaSky-AI/SkyRL/issues/96
We merge this PR to a separate branch `http-inf_engine-openai` for now for users to build on top of.
The intended use case is when users have their existing agent harness and want to do rollout with the existing code while using SkyRL.
After setting the following configs:
```
generator:
use_http_server_inference_engine_client: true
http_server_inference_engine_client_host: "127.0.0.1"
http_server_inference_engine_client_port: 8000
```
user can post OpenAI requests to `127.0.0.1:8000` in tools like `openai.OpenAI` or `litellm`. You can refer to `skyrl-train/examples/rollout_with_http_server_litellm.py` on how to use this feature.
Underlying-ly, when these configs are set, we launch a FastAPI server when calling …
> [Generator] Add FastAPI server for inference engine client

- skyrl-train/skyrl_train/trainer.py
- skyrl-train/skyrl_train/utils/trainer_utils.py
- skyrl-train/tests/cpu/test_trainer_utils.py
Adds a `validate_generation_output` function in `trainer_utils.py` with more robust validation of generation output format. Specifically, given 
```
class GeneratorOutput(TypedDict):
prompt_token_ids: List[List[int]]
response_ids: List[List[int]]
rewards: Union[List[float], List[List[float]]]
loss_masks: List[List[int]]
stop_reasons: Optional[List[str]]
rollout_metrics: Optional[Dict[str, Any]]
```
We expect
- all list attributes should have the same length  and be the same length as the input batch of prompts at dim=0
- non zero length lists
- response_ids, loss masks, and rewards (if token level rewards) should be the same length
- the sum of loss masks should be non-zero (logging a warning if it is not)
verified gsm8k run still works:
> [trainer] add more robust generation output validation

- skyrl-train/docs/configuration/config.rst
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/utils/ppo_utils.py
- skyrl-train/tests/cpu/algorithms/test_losses.py
This PR adds support for [Group Sequence Policy Optimization (GSPO)](https://arxiv.org/abs/2507.18071), the hotness du jour from Alibaba Qwen. The implementation in this PR is loosely based on [this one](https://github.com/huggingface/trl/pull/3775) from TRL. It adds an `importance_sampling_level` config option which can be `token` (PPO/GRPO) or `sequence` (GSPO).
I ran a short/small GSM8k run with Qwen2.5-0.5B and the loss curves look okay:
However, I had to hack a few things to get this to run on Datadog's cloud infra (including changing some dependency versions) so I'd encourage one of the maintainers to reproduce these results locally before merging.
> [Trainer] GSPO support

- skyrl-train/docs/configuration/config.rst
- skyrl-train/skyrl_train/utils/utils.py
This PR forward the `MLFLOW_TRACKING_URI` and `MLFLOW_TRACKING_TOKEN` environment variable to the ray runtime env during its initialisation.
> Forward mlflow env vars to ray runtime env

- skyrl-train/skyrl_train/utils/utils.py
Before this PR, running `{colocate_all=false, local vllm engine, NCCL weight_sync_backend, any TP size}` would run into the following issue: https://gist.github.com/CharlieFRuan/18f78a803ff72fa67132d2b80b4f48c4
This is because vLLM sets `NCCL_CUMEM_ENABLE=0`, and we need to match that. See this doc for more https://docs.vllm.ai/en/v0.9.2/usage/troubleshooting.html?h=nccl_cumem_enable#known-issues
> [Fix] Add NCCL_CUMEM_ENABLE=0 for vllm to address weight sync error

- skyrl-train/skyrl_train/utils/ppo_utils.py
- skyrl-train/skyrl_train/utils/utils.py
- skyrl-train/tests/cpu/utils/test_ppo_utils.py
This PR does two things.
Currently, when we run unit tests like `test_policy_vllm_e2e.py`, in the same Python process, we do `ray.init()` and `ray.shutdown()` for each unit test. However, the states of `BaseFunctionRegistry` persist across each init/shutdown. This makes attributes like `BaseFunctionRegistry._actor_handle` outdated -- as  the actor is killed by `ray.shutdown()`.
This leads to the Registry mistakenly thinking the actor is still alive, leading to error in `BaseFunctionRegistry` for subsequent unit tests.
To fix this, we check whether the actor is still alive with `ray.get_actor(cls._actor_name)` in `BaseFunctionRegistry.sync_with_actor()`. If dead, we reset the attributes accordingly.
An alternative fix is to call `BaseFunctionRegistry.reset()` before each `ray.shutdown()` …
> [Fix] Reset registries in BaseFunctionRegistry.sync_with_actor() when needed and fix registry reset

- skyrl-train/examples/async/async_trainer.py
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/inference_engines/base.py
- skyrl-train/skyrl_train/inference_engines/inference_engine_client.py
- skyrl-train/skyrl_train/inference_engines/ray_wrapped_inference_engine.py
- skyrl-train/skyrl_train/inference_engines/remote_inference_engine.py
- skyrl-train/skyrl_train/inference_engines/sglang/sglang_engine.py
- skyrl-train/skyrl_train/inference_engines/vllm/vllm_engine.py
- skyrl-train/skyrl_train/inference_engines/vllm/vllm_server.py
- skyrl-train/skyrl_train/trainer.py
- skyrl-train/skyrl_train/utils/__init__.py
- skyrl-train/skyrl_train/utils/utils.py
- skyrl-train/skyrl_train/workers/deepspeed/deepspeed_worker.py
- skyrl-train/skyrl_train/workers/fsdp/fsdp_worker.py
- skyrl-train/skyrl_train/workers/worker.py
- skyrl-train/tests/cpu/algorithms/test_losses.py
- skyrl-train/tests/cpu/test_trainer.py
- skyrl-train/tests/gpu/test_grpo_sp_sanity.py
Supports a list of weights during weight sync for colocated training. During colocated training, we use CUDA IPC for weight syncing. The current impl is syncing weights param by param, which can be pretty inefficient. In this PR, we sycn tensors in batches of a configurable parameter (default 1GB). That is, we collect ipc metadata until the total size of underlying tensors is 1GB and forward to the inference engine. Each TP rank will materialize all tensors in this list  (i.e additional memory usage of 1GB here) and issue a single load_weights call. 
**How much faster is it?**
Even for a 14B model on a 8xH100 node (TP2), the weight sync time can reduce from around 4.4s to 1.6s (60% reduction). This will matter much more for larger models. 
This PR is needed for the FlashRL integration to …
> [FlashRL 2/N] Support list of weights during weight sync for colocated training

- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
This PR moves the `chat_end_index` to after the `chat_history` has been modified by the `env.init` function, to get the right number.
In our use case, we are injecting the system prompt in addition to the user message in the `env.init`, so the length changes before and after.
In this case the `chat_end_index` is 1 instead of 2. We think it might be causing some bugs down the line, leading to this assertion error:
```
AssertionError: Response ids and loss masks must have the same length, for sample 0 got 27 and 50
```
Resolves #183
> get chat_end_index after env init

- skyrl-train/skyrl_train/entrypoints/main_base.py
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
- skyrl-train/skyrl_train/inference_engines/base.py
- skyrl-train/skyrl_train/inference_engines/inference_engine_client.py
- skyrl-train/skyrl_train/inference_engines/remote_inference_engine.py
- skyrl-train/skyrl_train/inference_engines/sglang/sglang_engine.py
- skyrl-train/skyrl_train/inference_engines/sglang/sglang_server.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator.py
- skyrl-train/tests/cpu/generators/test_skyrl_gym_generator_chat_templating.py
- skyrl-train/tests/gpu/test_engine_generation.py
- skyrl-train/tests/gpu/test_skyrl_gym_generator.py
This PR ensures token-in-token-out rollout in most codepaths in SkyRL. The motivation of having token-in/out is described in this issue https://github.com/NovaSky-AI/SkyRL/issues/123
- While `response_ids` were already added for local vLLM engine in https://github.com/NovaSky-AI/SkyRL/pull/145, this PR supports this field for {vllm, sglang} x {remote engine, local engine}.
- SGLang remote engine:
- with `--skip-tokenizer-init` passed to SGLang engine creation, we can use `/generate` endpoint, which can take in batch input via HTTP, performing token-in-token-out (almost exactly the same as the python `.generate()`)
- SGLang local engine: same thing
- vLLM remote engine:
- While `/completions` can take token-in, it does not do token-out. vLLM's `/generate` is demo-only according to its doc. …
> [Generator] Support token-in-token-out rollout

- skyrl-train/skyrl_train/inference_engines/utils.py
By default, SkyRL currently calls inference engines with `skip_special_tokens=False`. This causes special tokens (e.g. `<|im_end|>`) to appear in the decoded text output. This means that the decoded output passed in to environments via `env.step(output)` (in the `agent_loop`) may include stop tokens, which likely isn’t expected behavior.
This PR addresses that by setting skip_special_tokens=True when sampling from vLLM and SGLang.
I briefly validated this change functions as intended by comparing two runs w/ and w/o, and am no longer seeing the `<|im_end|>` tokens when I log `output`.
> [Fix] Set skip_special_tokens to True in default sampling params

- skyrl-train/docs/tutorials/new_env.rst
#207 just corrected an error in `BaseTextEnv`. This PR propagates it to the docs
> [doc fix] Correcting `ObsType` in `BaseTextEnv`

- skyrl-train/docs/index.rst
- skyrl-train/docs/tutorials/skyrl_gym_generator.rst
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
This PR adds a documentation page detailing the behavior of `SkyRLGymGenerator`, including the 3 codepaths described in  https://github.com/NovaSky-AI/SkyRL/pull/152, how multi-turn and single-turn rollouts/tokenizations work, and how token-in-token-out is enforced.
As a result, we can remove some bulky comments in `skyrl_gym_generator.py`
> [Doc] Add a doc page for SkyRLGymGenerator, multi-turn rollout/tokenization

- skyrl-train/tests/gpu/test_worker_offload.py
- skyrl-train/tests/gpu/utils.py
Fix small bug in worker offload test so we can check #212
```bash
uv run --extra dev --extra deepspeed --isolated pytest tests/gpu/test_worker_offload.py::test_critic_policy_offload_memory_and_correctness -k deepspeed
```
> [tests] Fix gpu offload test

- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
This pull request addresses a bug in the `retokenize_chat_history` codepath within SkyRLGymGenerator. The issue arose when env.init() altered the length of the chat_history, as the original length was incorrectly assumed. The fix introduces initial_chat_history_length to correctly capture the length of the chat history after the env.init() call. This new variable is then used to accurately slice the chat history, separating the initial prompt from the generated turns.
This PR fixes this issue and closes https://github.com/NovaSky-AI/SkyRL/issues/213
> [Fix][Generator] Correct chat history length for retoknenize codepath with env.init

- skyrl-train/examples/search/run_search_conversation_format.sh
- skyrl-train/examples/text_to_sql/run_skyrl_sql_conversation_format.sh
Missed a change before merging #190
> [Examples] Minor fix after #190

- skyrl-train/skyrl_train/distributed/strategy.py
- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
- skyrl-train/skyrl_train/utils/tracking.py
- skyrl-train/skyrl_train/utils/trainer_utils.py
- skyrl-train/tests/cpu/test_trainer_utils.py
There are various places in the repo where we do `print("WARNING:...")` which can be annoying. This PR changes them to `logger.warning()`.
There are still various print statements throughout the repo, but I will fix the warnings one first.
Related to https://github.com/NovaSky-AI/SkyRL/issues/168
> [logs] Change print warnings to logger.warning

- skyrl-train/tests/gpu/gpu_ci/test_skyrl_gym_generator.py
After https://github.com/NovaSky-AI/SkyRL/pull/190, we need to pass `stop` as sampling params for multiturn search / text2sql. Without it, the GPU CI will likely fail
> [Fix][CI] Fix GPU CI where search needs stop param

- skyrl-train/ci/gpu_ci_run.sh
- skyrl-train/ci/gpu_e2e_test_run.sh
- skyrl-train/tests/gpu/gpu_ci/test_engine_generation.py
Fixes failing sglang test after #234 
The failure:
```bash
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/gpu/gpu_ci/test_engine_generation.py::test_inference_engines_generation[sglang] - TypeError: run_batch_generation() missing 1 required positional argument: 'sampling_params'
====== 1 failed, 2 passed, 25 deselected, 32 warnings in 94.94s (0:01:34) ======
sys:1: DeprecationWarning: builtin type swigvarlink has no __module__ attribute
```
After fixes in this PR: 
```bash
...
=========================================================================================== warnings summary ========================================================================================== …
```
> [Fix] Fix failing sglang test after #234 

- skyrl-train/skyrl_train/generators/skyrl_gym_generator.py
Makes all calls to environment in SkyRLGymGenerator asynchronous.
Calls to env.init/step/close may have expensive blocking operations, in which case the entire process is blocked waiting for each env method call to complete sequentially. By submitting all environment calls to a threadpool the same way we do for env.step, all blocking operations in the environment can happen concurrently.
I didn't add tests since it looks like this code path is covered by existing e2e tests and I'm not sure it's worth adding a specific test case for.
I did run this myself with my own environment and confirmed that my blocking network operations are now executed concurrently, resulting in significant time savings (about 15% reduction in step time)
> [Generator] Run env methods in threadpool executor

- skyrl-train/skyrl_train/inference_engines/vllm/vllm_engine.py
`request_logger` is a required argument.
> [fix] Add missing required argument to OpenAIServingChat

- skyrl-train/skyrl_train/trainer.py
\*sigh\*... missed a couple locations to remove an argument from `cleanup_old_checkpoints`, and CI caught it.
> [fix] Extra argument in `cleanup_old_checkpoints`

- skyrl-train/tests/gpu/gpu_ci/test_verifiers_generator.py
We cannot import `VerifiersGenerator` unless `--with verifiers` is included in the `uv` command. An error is thrown when pytest is collecting all tests and tries to import `VerifiersGenerator`.
This PR moves the import of `VerifiersGenerator` in the test into the test body so that it's only imported when executed. 
Confirmed that Verifiers integration tests still pass with the commands in the CI pipeline:
> [fix] Resolve CI error due to import error

- skyrl-train/skyrl_train/utils/utils.py
Brings back nicely-formatted logs (ie, coloring, bold, etc.) that was lost when the training loop moved off the head node.
Old:
New:
> [fix] Bring back pretty log formatting

- skyrl-train/examples/training_backends/megatron/run_megatron.sh
- skyrl-train/pyproject.toml
- skyrl-train/skyrl_train/utils/utils.py
- skyrl-train/skyrl_train/workers/megatron/megatron_worker.py
- skyrl-train/tests/gpu/test_megatron_worker.py
- skyrl-train/uv.lock
This PR makes sure that the flash-attn backend is chosen when flash_attn=True for the Megatron backend. Previously the backend for TransformerEngine was "auto" and was being overridden in the [`get_attention_backend` function ](https://github.com/NVIDIA/TransformerEngine/blob/release_v2.5/transformer_engine/pytorch/attention/dot_product_attention/utils.py#L916).
avg raw reward is slightly lower with flash-attn
Grad norm is a little lower with flash-attn 
But overall evals seem ok
> [trainer][megatron] Override fused attention with flash-attn when flash_attn=True for Megatron

- skyrl-train/tests/gpu/gpu_ci/test_skyrl_gym_generator.py
Our unit test checks whether, for turns=3, the final conversation generates 3 EOS token. This will not be the case when the model's generation stop due to length. To address, we do the following:
- In the dummy environment, change observation `"turn {i}"` to `"give me another solution {i}"`, which might make more sense for the model
- Increase max generate length from 1000 to 3000
- Final guard is to check when the stop reason is not `"stop"`, we don't check the number of EOS token IDs
> [Fix][CI] Address generator CI test fails when model stop reason is length

- skyrl-train/examples/async/main_async.py
- skyrl-train/examples/flash_rl/main_dapo_flashrl.py
- skyrl-train/examples/llm_as_a_judge/main_llm_judge.py
- skyrl-train/examples/terminal_bench/entrypoints/main_tbench.py
- skyrl-train/examples/terminal_bench/entrypoints/main_tbench_generate.py
- skyrl-train/skyrl_train/entrypoints/main_base.py
This PR deletes the examples `uv run ...` launch commands added to the top of many `main` files.
A few users have hit a mysterious `uv` error, and I learned it's because they were using the default command in `main_base.py`, which is incorrect. Here was the error:
```
AssertionError: uv run command [] is not a suffix of command line ['uv', 'run', '--isolated', '--extra', 'vllm', '--extra', 'sandboxes', '-m', 'examples.terminal_bench.main_tbench_generate']
```
Users shouldn't actually run these commands directly, it's much much better to go through a `.sh` file in the examples.
> [tiny fix] Remove the example launch command for main files

- skyrl-train/skyrl_train/inference_engines/inference_engine_client.py
- skyrl-train/skyrl_train/inference_engines/utils.py
- skyrl-train/tests/cpu/test_route_prompts_to_engines.py
This PR removes `_generate_batched()` and `_generate_with_trajectory_routing()` in `InferenceEngineClient` by adding a helper method that:
```python
def route_prompts_to_engines(
num_prompts: int, num_inference_engines: int, trajectory_ids: Optional[Union[list[int], list[str]]]
) -> dict[int, list[int]]:
```
returning a mapping from engine ID to the prompt IDs they work on.
This removes the duplicated code when gathering the output.
In addition, for the `/completions` PR, this will be highly beneficial. Without this PR we would need to duplicate `_generate_with_trajectory_routing()` and `_generate_batched()`, which are for `InferenceEngineInput` and make another pair for `CompletionRequest`.
We also change `hash()` to `int.from_bytes(hashlib.sha256(str(x).encode()).digest(), "big")`, …
> [InfEngineClient] Extract out routing logic to a helper

- skyrl-train/docs/examples/mini_swe_agent.rst
- skyrl-train/examples/mini_swe_agent/mini_swe_generator.py
- skyrl-train/examples/mini_swe_agent/mini_swe_utils.py
- skyrl-train/examples/mini_swe_agent/run_mini_swe_30B.sh
- skyrl-train/examples/mini_swe_agent/run_mini_swe_8B.sh
Minor cleanup for the Mini-SWE-Agent example that were missed in #222 .
> [Examples][Fix] Minor cleanup for the Mini-SWE-Agent example

- skyrl-train/skyrl_train/inference_engines/ray_wrapped_inference_engine.py
Sometimes it is desirable to use a development version of vLLM by installling from source. With vLLM's version convention, the dev version looks something like: `0.1.dev8666+g0e3bb543f`.  Currently, using a dev version will fail due to a strict version check. This PR makes a minor edit to skip the version check if a dev version is being used.
> [vLLM] Skip the version check if an development version is being used

- skyrl-train/ci/gpu_ci_run.sh
GPU CI is failing locally with the following error:
```bash
(base) ray@ip-10-0-145-16:~/default/gen-tracker/skyrl-train$ bash ci/gpu_ci_run.sh
......
ImportError while loading conftest '/home/ray/default/gen-tracker/skyrl-train/tests/gpu/conftest.py'.
tests/gpu/conftest.py:3: in <module>
from tests.gpu.utils import ray_init_for_tests
tests/gpu/utils.py:18: in <module>
from skyrl_train.workers.worker import PPORayActorGroup
skyrl_train/workers/worker.py:25: in <module>
from transformers import PreTrainedModel
../../../.cache/uv/builds-v0/.tmp27LTUz/lib/python3.12/site-packages/transformers/utils/import_utils.py:2305: in __getattr__
raise ModuleNotFoundError(
E   ModuleNotFoundError: Could not import module 'PreTrainedModel'. Are this object's requirements defined correctly?
```
The root …
> [GPU CI] Fix deepspeed dependency in GPU CI

- skyrl-train/pyproject.toml
- skyrl-train/uv.lock
In #222 , we added the mini-swe-agent integration. Since the integration requires a commit after https://github.com/SWE-agent/mini-swe-agent/commit/4f5d445e99d13b5482478c23508bf2fbf7c0670c, we installed from source at the time. 
However, a new version 1.12.0 was released recently which includes the above commit. This PR updates the mini-swe-agent version in the TOML and the lock file.
> [Dependencies] Use release version for Mini-SWE-Agent

- skyrl-train/docs/configuration/config.rst
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
We've set the default for the Ref model to be `cpu_offload: true`. However, this is pretty non-intuitive and can lead to a subtle performance drop. We should use default `false`
> [Config] Fix `cpu_offload` default for Ref model

- skyrl-train/docs/configuration/config.rst
- skyrl-train/skyrl_train/config/ppo_base_config.yaml
- skyrl-train/skyrl_train/entrypoints/main_base.py
- skyrl-train/skyrl_train/inference_engines/ray_wrapped_inference_engine.py
Resolves #318 
Adds support for specifying inference engine args in the training config and CLI override arguments, which are passed directly to the vLLM or SGLang Engine init. For example, to specify vLLM's tool params, you can add the following to the training script (note the `+`, which is required):
```
+generator.engine_init_kwargs.enable_auto_tool_choice=true \
+generator.engine_init_kwargs.tool_call_parser="hermes"
```
> Plumb `engine_init_kwargs` from CLI to inference engine

- skyrl-train/ci/gpu_ci_run.sh
- skyrl-train/tests/gpu/gpu_ci/test_trainer_full_checkpointing.py
#298 broke GPU CI a bit: 
1. Megatron related dependencies have not been resolved properly on `main` yet, and this test should be skipped.
2. We use a simple 4xL4 instance, but then the test was modified in #298 to request 8 GPUs (non-colocated training)
> [Tests] Fix GPU CI failures after #298

- skyrl-train/examples/async/async_run_gsm8k.sh
- skyrl-train/examples/async/async_trainer.py
- skyrl-train/scripts/full_context/trainer_full_ctx.py
- skyrl-train/tests/gpu/test_grpo_sp_sanity.py
Fixes async trainer example after #298. We renamed `setup_policy_and_generator` to `init_weight_sync_state`
> [Fix] Fix async trainer after #298

- skyagent/examples/run_skyrl/trainer.py
- skyrl-train/skyrl_train/trainer.py
Fixes `all_envs` repetition in `_prepare_generator_input` for evaluation.
> [Fix] Fix n samples for evaluation in trainer

- skyrl-train/examples/gsm8k/run_generation_gsm8k.sh
By default we sleep() the inference engines after construction so that we can initialize the training workers. When we created the generation-only entrypoint, we still followed this sleep() code path, but had to wake_up() the inference engines for generation, and wake_up() can corrupt weights. 
This PR disables `colocate_all` in the example script as a quick fix. I will send out a (hopefully more elegant) solution to this, and add a test to cover it
> [fix] Fix broken default arguments in generation entrypoint

- skyrl-train/skyrl_train/trainer.py
As title. We need to exclude the observation tokens because the rollout logprobs for these tokens will be 0 (dummy) and thus the overall logprobs difference will be artificially inflated.
> [Metrics] Ignore observation tokens while calculating rollout train logprobs difference 

- skyrl-train/skyrl_train/distributed/megatron/megatron_strategy.py
Megatron's multi-node distributed checkpointing creates short-lived background workers to handle checkpointing, which are spawned with `os.fork()`. The kernel generally must ensure a full copy-on-write can be made of the parent process, which is memory heavy during trining. Ray explicitly recommends not forking in application code and to use spawn / Ray actors instead.
These PR updates the checkpoint worker to by persistent, which avoids `fork` and instead `spawn`s the persistent worker. This matches Megatron's (not so well publicized) findings discussed briefly [here](https://github.com/NVIDIA/nvidia-resiliency-ext/pull/108#issue-3203755296). 
For reference, we originally saw this error during checkpointing:
```
(skyrl_entrypoint pid=819281, ip=172.25.105.154)   File …
```
> [fix] Megatron dist checkpoint should use spawn, not fork

- skyrl-train/examples/megatron/run_fsdp_baseline.sh
- skyrl-train/examples/megatron/run_megatron.sh
- skyrl-train/examples/megatron/run_megatron_moonlight.sh
- skyrl-train/examples/megatron/run_megatron_qwen3-235b-a22b.sh
- skyrl-train/examples/megatron/run_megatron_qwen3-30b-a3b.sh
- skyrl-train/examples/megatron/run_search_megatron.sh
- skyrl-train/pyproject.toml
- skyrl-train/skyrl_train/config/megatron_config/policy.yaml
- skyrl-train/skyrl_train/config/megatron_config/ref.yaml
- skyrl-train/uv.lock
More cleanup for megatron examples, and bump mbridge version to 0.15.1 for some bug fixes with tied weight embeddings.
> [megatron] cleaning up examples + bump mbridge version

- skyrl-tx/README.md
- skyrl-tx/pyproject.toml
This changes the package name and uploads the package to pypi so we can reserve it. Likely the pypi package name will keep being `skyrl-tx` going forward and the python folder will keep being `tx` so the imports and executable are short.
> [skyrl-tx] Change package name

- skyrl-train/skyrl_train/utils/trainer_utils.py
- skyrl-train/tests/cpu/utils/test_io.py
Minor clean up. Remove `get_latest_checkpoint_step()` and its unit test since it is not used anywhere. Instead we have been using `Trainer.load_checkpoints` directly.
> [Cleanup] Remove get_latest_checkpoint_step as not used anywhere

- skyrl-tx/tx/layers/lora.py
I noticed now that we are setting the out-of-rank entries to zero in update_adapter_config, we actually don't need the rank masking in the forward pass any more, so this PR removes it.
> [tx] Remove the LoRA masking
